# Generated by Django 6.0 on 2026-02-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_propertytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertytype_name', models.CharField(max_length=30)),
            ],
        ),
    ]
