# Generated by Django 6.0 on 2026-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bhk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_furnish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnish_name', models.CharField(max_length=30)),
            ],
        ),
    ]
