# Generated by Django 6.0 on 2026-02-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_bhk_tbl_furnish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bhk',
            name='propertytype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_propertytype'),
        ),
    ]
