# Generated by Django 5.2.11 on 2026-03-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_furnish_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
