# Generated by Django 5.2.8 on 2025-12-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
        ('Guest', '0004_tbl_seller_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=30)),
                ('property_description', models.CharField(max_length=30)),
                ('property_date', models.CharField(max_length=30)),
                ('property_price', models.CharField(max_length=30)),
                ('property_photo', models.CharField(max_length=30)),
                ('property_status', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
            ],
        ),
    ]
