# Generated by Django 5.2.8 on 2025-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_property',
            name='property_photo',
            field=models.FileField(upload_to='Assets/Property/Photo/'),
        ),
    ]
