# Generated by Django 5.2.8 on 2025-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_tbl_property_property_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_property',
            name='property_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
