# Generated by Django 5.2.8 on 2025-12-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_tbl_property_property_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.FileField(upload_to='Assets/Property/Gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_property')),
            ],
        ),
    ]
