# Generated by Django 5.2.8 on 2025-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_tbl_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_property',
            name='property_typestatus',
            field=models.IntegerField(null=True),
        ),
    ]
