# Generated by Django 5.2.8 on 2025-12-17 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_renter_renter_status'),
        ('Seller', '0005_tbl_property_property_typestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_property',
            name='renter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_renter'),
        ),
    ]
