# Generated by Django 6.0 on 2026-02-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_propertytype'),
        ('Seller', '0006_tbl_property_renter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_property',
            name='propertytype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_propertytype'),
        ),
    ]
