# Generated by Django 6.0 on 2026-02-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_furnish_propertytype'),
        ('Seller', '0007_tbl_property_propertytype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_property',
            name='bhk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_bhk'),
        ),
        migrations.AddField(
            model_name='tbl_property',
            name='furnish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_furnish'),
        ),
    ]
