# Generated by Django 5.2.11 on 2026-03-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_tbl_property_bhk_id_tbl_property_furnish_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_auctionhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionhead_amount', models.CharField(max_length=30)),
                ('auctionhead_date', models.DateField(auto_now_add=True)),
                ('auctionhead_todate', models.DateField()),
                ('auction_starttime', models.CharField(max_length=30)),
                ('auctionhead_status', models.IntegerField(default=0)),
                ('auction_totalamount', models.CharField(max_length=30)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_property')),
            ],
        ),
    ]
