# Generated by Django 5.2.8 on 2025-12-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
        ('Guest', '0002_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_contact', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=100)),
                ('seller_photo', models.FileField(upload_to='Assets/User/')),
                ('seller_proof', models.FileField(upload_to='Assets/User/')),
                ('seller_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
