# Generated by Django 5.2.8 on 2025-12-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seller',
            name='seller_status',
            field=models.IntegerField(default=0),
        ),
    ]
