# Generated by Django 5.2.8 on 2025-12-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory'),
        ('Guest', '0004_tbl_seller_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=30)),
                ('renter_email', models.CharField(max_length=30)),
                ('renter_contact', models.CharField(max_length=30)),
                ('renter_address', models.CharField(max_length=100)),
                ('renter_photo', models.FileField(upload_to='Assets/User/')),
                ('renter_proof', models.FileField(upload_to='Assets/User/')),
                ('renter_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
