# Generated by Django 5.2.8 on 2025-12-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_renter',
            name='renter_status',
            field=models.IntegerField(default=0),
        ),
    ]
