# Generated by Django 5.2.8 on 2025-12-17 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_tbl_renter_renter_status'),
        ('Seller', '0006_tbl_property_renter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_propertybuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertybuying_date', models.DateField(auto_now_add=True)),
                ('propertybuying_amount', models.CharField(max_length=30)),
                ('propertybuying_status', models.IntegerField(default=0)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
