# Generated by Django 6.0 on 2026-01-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_renter_renter_status'),
        ('Seller', '0006_tbl_property_renter_id'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_propertybooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertybooking_date', models.DateField(auto_now_add=True)),
                ('propertybooking_fromdate', models.DateField()),
                ('propertybooking_todate', models.DateField()),
                ('propertybooking_amount', models.CharField(max_length=30)),
                ('propertybooking_status', models.IntegerField(default=0)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_property')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
