# Generated by Django 6.0 on 2026-01-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_propertybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_propertybookingpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertybookingpayment_date', models.DateField(auto_now_add=True)),
                ('propertybookingpayment_amount', models.CharField(max_length=30)),
                ('propertybookingpayment_status', models.IntegerField(default=0)),
                ('propertybooking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_propertybooking')),
            ],
        ),
    ]
