# Generated by Django 6.0 on 2026-01-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_propertybookingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_propertybooking',
            name='propertybooking_fromdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_propertybooking',
            name='propertybooking_todate',
            field=models.DateField(null=True),
        ),
    ]
