# Generated by Django 6.0 on 2026-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_propertybuing',
            name='propertybuying_propertytype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
