# Generated by Django 6.0 on 2026-02-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_propertybuing_propertybuying_propertytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_propertybuing',
            name='propertybuying_propertytype',
        ),
    ]
