# Generated by Django 5.2.11 on 2026-03-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_renter_renter_status'),
        ('Seller', '0009_tbl_auctionhead'),
        ('User', '0010_remove_tbl_propertybuing_propertybuying_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_auctionbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionbody_amount', models.CharField(max_length=30)),
                ('auctionbody_status', models.IntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_auctionhead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timmer', models.TimeField()),
                ('timmer_status', models.IntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.tbl_auctionhead')),
            ],
        ),
    ]
